from domain.entities.proposicao import Proposicao
from infrastructure.adapters.base_adapter import ProposicaoAdapter


class CamaraMockAdapter(ProposicaoAdapter):
    """Adapter mock da API da Câmara dos Deputados.

    Normaliza dados no formato da Câmara para a entidade de domínio Proposicao.
    Substitua este adapter por CamaraAdapter quando a integração real for implementada.
    """

    def buscar(self) -> list[Proposicao]:
        return [
            Proposicao(
                id="cam-1",
                tipo="PL",
                numero="1234",
                ano=2023,
                ementa="Dispõe sobre a transparência nos processos de licitação pública e contratação de serviços pelo poder executivo federal.",
                ementa_resumida="Transparência em licitações públicas",
                autor="João Silva",
                orgao_origem="Câmara dos Deputados",
                status="Em tramitação",
                orgao_atual="CCJ",
                data_apresentacao="2023-03-15",
                data_ultima_movimentacao="2024-11-20",
                tempo_total_dias=615,
                tem_atraso=True,
                tem_previsao_ia=True,
                previsao_aprovacao_dias=180,
                tags=["licitação", "transparência", "administração pública"],
            ),
            Proposicao(
                id="cam-2",
                tipo="PEC",
                numero="45",
                ano=2023,
                ementa="Altera o artigo 195 da Constituição Federal para modificar as contribuições sociais destinadas ao custeio da seguridade social.",
                ementa_resumida="Reforma tributária das contribuições sociais",
                autor="Maria Souza",
                orgao_origem="Câmara dos Deputados",
                status="Aprovada",
                orgao_atual="Senado Federal",
                data_apresentacao="2023-01-10",
                data_ultima_movimentacao="2024-06-30",
                tempo_total_dias=536,
                tem_atraso=False,
                tem_previsao_ia=False,
                tags=["tributário", "previdência", "constituição"],
            ),
            Proposicao(
                id="cam-3",
                tipo="PL",
                numero="2891",
                ano=2024,
                ementa="Institui o marco regulatório para uso de inteligência artificial na administração pública e no setor privado.",
                ementa_resumida="Marco regulatório da inteligência artificial",
                autor="Carlos Mendes",
                orgao_origem="Câmara dos Deputados",
                status="Em tramitação",
                orgao_atual="CTASP",
                data_apresentacao="2024-02-05",
                data_ultima_movimentacao="2024-12-01",
                tempo_total_dias=300,
                tem_atraso=False,
                tem_previsao_ia=True,
                previsao_aprovacao_dias=240,
                tags=["tecnologia", "inteligência artificial", "regulação"],
            ),
            Proposicao(
                id="cam-4",
                tipo="MP",
                numero="1185",
                ano=2023,
                ementa="Estabelece medidas emergenciais para apoio a municípios em situação de calamidade pública decorrente de desastres naturais.",
                ementa_resumida="Apoio emergencial a municípios em calamidade",
                autor="Poder Executivo",
                orgao_origem="Câmara dos Deputados",
                status="Sancionada",
                orgao_atual="Presidência da República",
                data_apresentacao="2023-09-01",
                data_ultima_movimentacao="2023-11-15",
                data_encerramento="2023-11-15",
                tempo_total_dias=75,
                tem_atraso=False,
                tem_previsao_ia=False,
                tags=["calamidade", "emergência", "municípios"],
            ),
            Proposicao(
                id="cam-5",
                tipo="PL",
                numero="3042",
                ano=2022,
                ementa="Altera a Lei de Responsabilidade Fiscal para incluir metas de redução de emissões de gases de efeito estufa no planejamento orçamentário.",
                ementa_resumida="Orçamento verde e metas climáticas",
                autor="Ana Lima",
                orgao_origem="Câmara dos Deputados",
                status="Arquivada",
                orgao_atual="Câmara dos Deputados",
                data_apresentacao="2022-05-20",
                data_ultima_movimentacao="2023-02-10",
                data_encerramento="2023-02-10",
                tempo_total_dias=266,
                tem_atraso=False,
                tem_previsao_ia=False,
                tags=["meio ambiente", "fiscal", "clima"],
            ),
        ]
