"""add status_original to proposicao

Revision ID: 0d164b88bc9d
Revises: 71f8ba3e30f7
Create Date: 2026-06-08 14:47:50.290539

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d164b88bc9d"
down_revision: str | Sequence[str] | None = "71f8ba3e30f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.add_column(
        "proposicao",
        sa.Column("status_original", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###

    # --- Migração de Dados Retroativa ---
    # 1. Copia o status bruto atual para a nova coluna status_original
    op.execute(
        "UPDATE proposicao SET status_original = status WHERE status_original IS NULL"
    )

    # 2. Normaliza o campo status baseando-se no texto original (Mapeamento básico SQL)
    # Sancionada
    op.execute(
        "UPDATE proposicao SET status = 'Sancionada' WHERE status_original ILIKE '%SANCIONAD%' OR status_original ILIKE '%NORMA JURÍDICA%'"
    )
    # Vetada
    op.execute(
        "UPDATE proposicao SET status = 'Vetada' WHERE status_original ILIKE '%VETAD%'"
    )
    # Arquivada
    op.execute(
        "UPDATE proposicao SET status = 'Arquivada' WHERE status_original ILIKE '%REJEITAD%' OR status_original ILIKE '%ARQUIVAD%' OR status_original ILIKE '%PREJUDICAD%' OR status_original ILIKE '%RETIRAD%' OR status_original ILIKE '%APENSAD%'"
    )
    # Aprovada
    op.execute(
        "UPDATE proposicao SET status = 'Aprovada' WHERE status_original ILIKE '%APROVAD%'"
    )
    # Em Pauta
    op.execute(
        "UPDATE proposicao SET status = 'Em Pauta' WHERE status_original ILIKE '%PAUTA%'"
    )
    # Em Tramitação (Fallback para os demais casos que não foram normalizados acima)
    op.execute(
        "UPDATE proposicao SET status = 'Em Tramitação' WHERE status NOT IN ('Sancionada', 'Vetada', 'Arquivada', 'Aprovada', 'Em Pauta')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proposicao", "status_original")
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("perfil", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###
