"""create transit steps table

Revision ID: 102767e9a1c3
Revises: e1dbfbfbec74
Create Date: 2026-06-27 15:51:13.510343

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "102767e9a1c3"
down_revision: str | Sequence[str] | None = "e1dbfbfbec74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transit_step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposicao_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("casa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tipo_passo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data_entrada", sa.DateTime(), nullable=False),
        sa.Column("data_saida", sa.DateTime(), nullable=True),
        sa.Column("duracao_dias", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposicao_id"], ["proposicao.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transit_step_casa"), "transit_step", ["casa"], unique=False
    )
    op.create_index(
        op.f("ix_transit_step_data_entrada"),
        "transit_step",
        ["data_entrada"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transit_step_data_saida"), "transit_step", ["data_saida"], unique=False
    )
    op.create_index(
        op.f("ix_transit_step_proposicao_id"),
        "transit_step",
        ["proposicao_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transit_step_tipo_passo"), "transit_step", ["tipo_passo"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transit_step_tipo_passo"), table_name="transit_step")
    op.drop_index(op.f("ix_transit_step_proposicao_id"), table_name="transit_step")
    op.drop_index(op.f("ix_transit_step_data_saida"), table_name="transit_step")
    op.drop_index(op.f("ix_transit_step_data_entrada"), table_name="transit_step")
    op.drop_index(op.f("ix_transit_step_casa"), table_name="transit_step")
    op.drop_table("transit_step")
    # ### end Alembic commands ###
