"""evolve_fase_analitica_and_add_periodo_fase

Revision ID: 613a85bc4cae
Revises: 0d164b88bc9d
Create Date: 2026-06-09 20:54:24.119446

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '613a85bc4cae'
down_revision: str | Sequence[str] | None = '0d164b88bc9d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobertura_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo_proposicao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_api_oficial', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobertura_snapshot_ano'), 'cobertura_snapshot', ['ano'], unique=False)
    op.create_index(op.f('ix_cobertura_snapshot_tipo_proposicao'), 'cobertura_snapshot', ['tipo_proposicao'], unique=False)
    op.create_table('periodo_fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fase_analitica_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('duracao_dias', sa.Integer(), nullable=True),
    sa.Column('recorrencia_numero', sa.Integer(), nullable=False),
    sa.Column('eh_fase_atual', sa.Boolean(), nullable=False),
    sa.Column('motivo_travamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_proposicao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rito', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_turno', sa.Integer(), nullable=True),
    sa.Column('subtipo_fase', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_sessao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origem_calculo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['fase_analitica_id'], ['fase_analitica.id'], ),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_periodo_analise_dashboard', 'periodo_fase', ['fase_analitica_id', 'rito', 'tipo_proposicao'], unique=False, postgresql_where='eh_fase_atual = TRUE')
    op.create_index('idx_periodo_cronologia', 'periodo_fase', ['data_inicio', 'data_fim'], unique=False)
    op.create_index('idx_periodo_proposicao_atual', 'periodo_fase', ['proposicao_id', 'eh_fase_atual'], unique=False)
    op.create_index(op.f('ix_periodo_fase_data_fim'), 'periodo_fase', ['data_fim'], unique=False)
    op.create_index(op.f('ix_periodo_fase_data_inicio'), 'periodo_fase', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_periodo_fase_eh_fase_atual'), 'periodo_fase', ['eh_fase_atual'], unique=False)
    op.create_index(op.f('ix_periodo_fase_fase_analitica_id'), 'periodo_fase', ['fase_analitica_id'], unique=False)
    op.create_index(op.f('ix_periodo_fase_proposicao_id'), 'periodo_fase', ['proposicao_id'], unique=False)
    op.create_index(op.f('ix_periodo_fase_rito'), 'periodo_fase', ['rito'], unique=False)
    op.create_index(op.f('ix_periodo_fase_tipo_proposicao'), 'periodo_fase', ['tipo_proposicao'], unique=False)
    op.add_column('fase_analitica', sa.Column('natureza', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='operacional'))
    op.add_column('fase_analitica', sa.Column('papel_fluxo', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='permanencia'))
    op.add_column('fase_analitica', sa.Column('permite_estoque_atual', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('fase_analitica', sa.Column('permite_metricas_tempo', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('fase_analitica', sa.Column('indica_fase_terminal', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('fase_analitica', sa.Column('justificativa_juridica', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fase_analitica', 'justificativa_juridica')
    op.drop_column('fase_analitica', 'indica_fase_terminal')
    op.drop_column('fase_analitica', 'permite_metricas_tempo')
    op.drop_column('fase_analitica', 'permite_estoque_atual')
    op.drop_column('fase_analitica', 'papel_fluxo')
    op.drop_column('fase_analitica', 'natureza')
    op.drop_index(op.f('ix_periodo_fase_tipo_proposicao'), table_name='periodo_fase')
    op.drop_index(op.f('ix_periodo_fase_rito'), table_name='periodo_fase')
    op.drop_index(op.f('ix_periodo_fase_proposicao_id'), table_name='periodo_fase')
    op.drop_index(op.f('ix_periodo_fase_fase_analitica_id'), table_name='periodo_fase')
    op.drop_index(op.f('ix_periodo_fase_eh_fase_atual'), table_name='periodo_fase')
    op.drop_index(op.f('ix_periodo_fase_data_inicio'), table_name='periodo_fase')
    op.drop_index(op.f('ix_periodo_fase_data_fim'), table_name='periodo_fase')
    op.drop_index('idx_periodo_proposicao_atual', table_name='periodo_fase')
    op.drop_index('idx_periodo_cronologia', table_name='periodo_fase')
    op.drop_index('idx_periodo_analise_dashboard', table_name='periodo_fase', postgresql_where='eh_fase_atual = TRUE')
    op.drop_table('periodo_fase')
    op.drop_index(op.f('ix_cobertura_snapshot_tipo_proposicao'), table_name='cobertura_snapshot')
    op.drop_index(op.f('ix_cobertura_snapshot_ano'), table_name='cobertura_snapshot')
    op.drop_table('cobertura_snapshot')
    # ### end Alembic commands ###
