"""create auditoria_coleta table

Revision ID: 86d18f3dcdb0
Revises: b3f102f30e6g
Create Date: 2026-06-11 16:31:45.414484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86d18f3dcdb0'
down_revision: Union[str, Sequence[str], None] = 'b3f102f30e6g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_job', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('itens_processados', sa.Integer(), nullable=False),
    sa.Column('mensagem_erro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_coleta_job_id'), 'auditoria_coleta', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_coleta_job_id'), table_name='auditoria_coleta')
    op.drop_table('auditoria_coleta')
    # ### end Alembic commands ###
