"""add_ml_fields_to_proposicao

Revision ID: a1e102f30d5f
Revises: 613a85bc4cae
Create Date: 2026-06-09 21:01:25.718832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1e102f30d5f"
down_revision: str | Sequence[str] | None = "613a85bc4cae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proposicao", sa.Column("numero_assinaturas", sa.Integer(), nullable=True)
    )
    op.add_column(
        "proposicao", sa.Column("numero_emendas", sa.Integer(), nullable=True)
    )
    op.add_column(
        "proposicao", sa.Column("autor_e_poder_executivo", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "proposicao", sa.Column("tema_economico", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proposicao", "tema_economico")
    op.drop_column("proposicao", "autor_e_poder_executivo")
    op.drop_column("proposicao", "numero_emendas")
    op.drop_column("proposicao", "numero_assinaturas")
    # ### end Alembic commands ###
