import type { Proposicao, MovimentacaoTramitacao } from '../types'

export const PROPOSICOES_MOCK: Proposicao[] = [
  {
    id: '1',
    tipo: 'PL',
    numero: '1234',
    ano: 2022,
    ementa: 'Institui o Programa Nacional de Desenvolvimento Sustentável para pequenos agricultores e dispõe sobre incentivos fiscais para produção orgânica.',
    ementaResumida: 'Programa Nacional de Desenvolvimento Sustentável para agricultores',
    autor: 'Dep. Maria Silva (PT/SP)',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Em tramitação',
    orgaoAtual: 'CFT',
    dataApresentacao: '2022-03-15',
    dataUltimaMovimentacao: '2024-01-10',
    tempoTotalDias: 726,
    temAtraso: true,
    atrasoCritico: true,
    temPrevisaoIA: true,
    previsaoAprovacaoDias: 180,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PL-1234-2022',
    tags: ['agricultura', 'sustentabilidade', 'fiscal'],
  },
  {
    id: '2',
    tipo: 'PEC',
    numero: '45',
    ano: 2023,
    ementa: 'Altera os artigos 155 e 156 da Constituição Federal para simplificar o sistema tributário nacional e unificar impostos sobre bens e serviços.',
    ementaResumida: 'Reforma tributária — unificação de impostos sobre bens e serviços',
    autor: 'Sen. João Costa (MDB/RJ)',
    orgaoOrigem: 'Senado Federal',
    status: 'Aprovada',
    orgaoAtual: 'Senado Federal',
    dataApresentacao: '2023-02-08',
    dataUltimaMovimentacao: '2023-12-20',
    dataEncerramento: '2023-12-20',
    tempoTotalDias: 315,
    temAtraso: false,
    atrasoCritico: true,
    temPrevisaoIA: false,
    linkOficial: 'https://www.senado.leg.br',
    codigoNormalizado: 'PEC-45-2023',
    tags: ['tributário', 'reforma', 'impostos'],
  },
  {
    id: '3',
    tipo: 'PL',
    numero: '789',
    ano: 2021,
    ementa: 'Dispõe sobre a regulamentação do trabalho remoto e teletrabalho, estabelecendo direitos e obrigações de empregados e empregadores.',
    ementaResumida: 'Regulamentação do trabalho remoto e teletrabalho',
    autor: 'Dep. Ana Ferreira (PSDB/MG)',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Sancionada',
    orgaoAtual: 'Presidência da República',
    dataApresentacao: '2021-06-10',
    dataUltimaMovimentacao: '2022-11-30',
    dataEncerramento: '2022-11-30',
    tempoTotalDias: 538,
    temAtraso: false,
    atrasoCritico: true,
    temPrevisaoIA: false,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PL-789-2021',
    tags: ['trabalho', 'home office', 'CLT'],
  },
  {
    id: '4',
    tipo: 'MP',
    numero: '1150',
    ano: 2023,
    ementa: 'Estabelece medidas emergenciais de apoio a municípios atingidos por desastres naturais, incluindo transferências especiais do Fundo de Participação dos Municípios.',
    ementaResumida: 'Apoio emergencial a municípios atingidos por desastres naturais',
    autor: 'Poder Executivo',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Em tramitação',
    orgaoAtual: 'CAS',
    dataApresentacao: '2023-05-20',
    dataUltimaMovimentacao: '2024-02-05',
    tempoTotalDias: 261,
    temAtraso: true,
    atrasoCritico: true,
    temPrevisaoIA: true,
    previsaoAprovacaoDias: 90,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'MP-1150-2023',
    tags: ['desastres', 'municípios', 'emergência'],
  },
  {
    id: '5',
    tipo: 'PEC',
    numero: '32',
    ano: 2020,
    ementa: 'Proposta de Emenda à Constituição que altera dispositivos sobre a organização e o funcionamento da Administração Pública Federal.',
    ementaResumida: 'Reforma administrativa — organização da Administração Pública Federal',
    autor: 'Poder Executivo',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Arquivada',
    orgaoAtual: 'CCJ',
    dataApresentacao: '2020-09-03',
    dataUltimaMovimentacao: '2022-12-31',
    dataEncerramento: '2022-12-31',
    tempoTotalDias: 849,
    temAtraso: true,
    atrasoCritico: true,
    temPrevisaoIA: false,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PEC-32-2020',
    tags: ['reforma administrativa', 'servidores', 'gestão pública'],
  },
  {
    id: '6',
    tipo: 'PL',
    numero: '2630',
    ano: 2020,
    ementa: 'Institui a Lei Brasileira de Liberdade, Responsabilidade e Transparência na Internet, dispondo sobre redes sociais e notícias falsas.',
    ementaResumida: 'Lei das Fake News — regulamentação das redes sociais',
    autor: 'Sen. Alessandro Vieira (PSDB/SE)',
    orgaoOrigem: 'Senado Federal',
    status: 'Aguardando votação',
    orgaoAtual: 'Câmara dos Deputados',
    dataApresentacao: '2020-06-30',
    dataUltimaMovimentacao: '2023-09-12',
    tempoTotalDias: 1322,
    temAtraso: true,
    atrasoCritico: true,
    temPrevisaoIA: true,
    previsaoAprovacaoDias: 365,
    linkOficial: 'https://www.senado.leg.br',
    codigoNormalizado: 'PL-2630-2020',
    tags: ['internet', 'fake news', 'redes sociais', 'liberdade de expressão'],
  },
  {
    id: '7',
    tipo: 'PL',
    numero: '3515',
    ano: 2021,
    ementa: 'Dispõe sobre a proteção de dados pessoais e altera a Lei nº 12.965, de 23 de abril de 2014, regulamentando o uso de dados biométricos.',
    ementaResumida: 'Proteção de dados biométricos e privacidade digital',
    autor: 'Dep. Paulo Magalhães (PSD/BA)',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Em análise',
    orgaoAtual: 'CTASP',
    dataApresentacao: '2021-11-22',
    dataUltimaMovimentacao: '2023-10-18',
    tempoTotalDias: 695,
    temAtraso: true,
    atrasoCritico: true,
    temPrevisaoIA: false,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PL-3515-2021',
    tags: ['LGPD', 'privacidade', 'dados pessoais', 'biometria'],
  },
  {
    id: '8',
    tipo: 'PLP',
    numero: '68',
    ano: 2024,
    ementa: 'Regulamenta o Imposto sobre Bens e Serviços (IBS) e a Contribuição sobre Bens e Serviços (CBS) nos termos da Emenda Constitucional nº 132.',
    ementaResumida: 'Regulamentação do IBS e CBS — implementação da reforma tributária',
    autor: 'Poder Executivo',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Em tramitação',
    orgaoAtual: 'CFT',
    dataApresentacao: '2024-01-18',
    dataUltimaMovimentacao: '2024-03-01',
    tempoTotalDias: 43,
    temAtraso: false,
    atrasoCritico: false,
    temPrevisaoIA: true,
    previsaoAprovacaoDias: 120,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PLP-68-2024',
    tags: ['tributário', 'IBS', 'CBS', 'reforma tributária'],
  },
  {
    id: '9',
    tipo: 'PL',
    numero: '572',
    ano: 2022,
    ementa: 'Altera a Lei nº 9.394, de 20 de dezembro de 1996, para incluir o ensino de educação financeira como disciplina obrigatória na educação básica.',
    ementaResumida: 'Educação financeira obrigatória no ensino básico',
    autor: 'Dep. Tabata Amaral (PDT/SP)',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Em tramitação',
    orgaoAtual: 'CDH',
    dataApresentacao: '2022-08-05',
    dataUltimaMovimentacao: '2023-11-20',
    tempoTotalDias: 472,
    temAtraso: false,
    atrasoCritico: true,
    temPrevisaoIA: true,
    previsaoAprovacaoDias: 200,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PL-572-2022',
    tags: ['educação', 'finanças', 'escola'],
  },
  {
    id: '10',
    tipo: 'PEC',
    numero: '6',
    ano: 2019,
    ementa: 'Modifica o sistema de previdência social e estabelece regras de transição, alterando a Constituição Federal.',
    ementaResumida: 'Reforma da previdência — novas regras e regime de transição',
    autor: 'Poder Executivo',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Aprovada',
    orgaoAtual: 'Senado Federal',
    dataApresentacao: '2019-02-20',
    dataUltimaMovimentacao: '2019-11-13',
    dataEncerramento: '2019-11-13',
    tempoTotalDias: 266,
    temAtraso: false,
    atrasoCritico: true,
    temPrevisaoIA: false,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PEC-6-2019',
    tags: ['previdência', 'INSS', 'aposentadoria', 'reforma'],
  },
  {
    id: '11',
    tipo: 'PL',
    numero: '4.173',
    ano: 2023,
    ementa: 'Regulamenta a tributação da renda auferida por pessoas físicas residentes no Brasil em aplicações financeiras no exterior.',
    ementaResumida: 'Tributação de investimentos no exterior por pessoas físicas',
    autor: 'Poder Executivo',
    orgaoOrigem: 'Câmara dos Deputados',
    status: 'Sancionada',
    orgaoAtual: 'Presidência da República',
    dataApresentacao: '2023-08-30',
    dataUltimaMovimentacao: '2023-12-12',
    dataEncerramento: '2023-12-12',
    tempoTotalDias: 104,
    temAtraso: false,
    atrasoCritico: false,
    temPrevisaoIA: false,
    linkOficial: 'https://www.camara.leg.br',
    codigoNormalizado: 'PL-4.173-2023',
    tags: ['tributário', 'investimentos', 'exterior', 'IR'],
  },
  {
    id: '12',
    tipo: 'PL',
    numero: '3.305',
    ano: 2023,
    ementa: 'Institui o Marco Legal da Inteligência Artificial no Brasil, estabelecendo princípios, direitos e obrigações para o desenvolvimento e uso de sistemas de IA.',
    ementaResumida: 'Marco Legal da Inteligência Artificial no Brasil',
    autor: 'Sen. Eduardo Gomes (PL/TO)',
    orgaoOrigem: 'Senado Federal',
    status: 'Em tramitação',
    orgaoAtual: 'CAS',
    dataApresentacao: '2023-04-19',
    dataUltimaMovimentacao: '2024-02-28',
    tempoTotalDias: 315,
    temAtraso: false,
    atrasoCritico: true,
    temPrevisaoIA: true,
    previsaoAprovacaoDias: 240,
    linkOficial: 'https://www.senado.leg.br',
    codigoNormalizado: 'PL-3.305-2023',
    tags: ['inteligência artificial', 'tecnologia', 'regulação', 'inovação'],
  },
]

export const MOVIMENTACOES_MOCK: Record<string, MovimentacaoTramitacao[]> = {
  '1': [
    { id: 'm1-6', proposicaoId: '1', data: '2024-01-10', orgao: 'CFT', descricao: 'Aguardando designação de relator na CFT', responsavel: undefined, diasNaEtapa: 95, temAtraso: false },
    { id: 'm1-5', proposicaoId: '1', data: '2023-10-07', orgao: 'CFT', descricao: 'Encaminhada à Comissão de Finanças e Tributação para análise do impacto fiscal', responsavel: 'Dep. Roberto Campos', diasNaEtapa: 44, temAtraso: false },
    { id: 'm1-4', proposicaoId: '1', data: '2023-08-24', orgao: 'CMADS', descricao: 'Aprovada com emendas na CMADS — parecer favorável ao incentivo à produção orgânica', responsavel: 'Dep. Marina Santos', diasNaEtapa: 210, temAtraso: true },
    { id: 'm1-3', proposicaoId: '1', data: '2023-01-26', orgao: 'CTASP', descricao: 'Aprovada na CTASP com parecer favorável às condições de trabalho rural', responsavel: 'Dep. Silvio Torres', diasNaEtapa: 180, temAtraso: false },
    { id: 'm1-2', proposicaoId: '1', data: '2022-07-31', orgao: 'CCJ', descricao: 'Aprovada na Comissão de Constituição e Justiça — constitucionalidade confirmada', responsavel: 'Dep. Arthur Lira', diasNaEtapa: 138, temAtraso: false },
    { id: 'm1-1', proposicaoId: '1', data: '2022-03-15', orgao: 'Câmara dos Deputados', descricao: 'Apresentação e leitura na plenário — encaminhada para análise inicial', responsavel: 'Dep. Maria Silva', diasNaEtapa: 0, temAtraso: false },
  ],
  '6': [
    { id: 'm6-7', proposicaoId: '6', data: '2023-09-12', orgao: 'Câmara dos Deputados', descricao: 'Aguardando inclusão na pauta do plenário da Câmara', responsavel: undefined, diasNaEtapa: 185, temAtraso: true },
    { id: 'm6-6', proposicaoId: '6', data: '2023-03-11', orgao: 'Câmara dos Deputados', descricao: 'Texto aprovado em Comissão Especial com 370 emendas — pronto para plenário', responsavel: 'Dep. Arthur Lira', diasNaEtapa: 330, temAtraso: true },
    { id: 'm6-5', proposicaoId: '6', data: '2022-04-16', orgao: 'Comissão Especial', descricao: 'Criação de Comissão Especial para análise do texto substitutivo', responsavel: 'Dep. Orlando Silva', diasNaEtapa: 290, temAtraso: false },
    { id: 'm6-4', proposicaoId: '6', data: '2021-07-01', orgao: 'Senado Federal', descricao: 'Aprovado no Senado com alterações e retornado à Câmara revisora', responsavel: 'Sen. Rodrigo Pacheco', diasNaEtapa: 365, temAtraso: true },
    { id: 'm6-3', proposicaoId: '6', data: '2020-06-30', orgao: 'CCJ — Senado', descricao: 'Aprovado na CCJ do Senado Federal', responsavel: 'Sen. Simone Tebet', diasNaEtapa: 95, temAtraso: false },
    { id: 'm6-2', proposicaoId: '6', data: '2020-03-27', orgao: 'Senado Federal', descricao: 'Aprovado em primeiro turno no Senado Federal com ampla maioria', responsavel: 'Sen. Rodrigo Pacheco', diasNaEtapa: 270, temAtraso: false },
    { id: 'm6-1', proposicaoId: '6', data: '2020-06-30', orgao: 'Senado Federal', descricao: 'Apresentação do PL 2630/2020 pelo Sen. Alessandro Vieira', responsavel: 'Sen. Alessandro Vieira', diasNaEtapa: 0, temAtraso: false },
  ],
  '12': [
    { id: 'm12-4', proposicaoId: '12', data: '2024-02-28', orgao: 'CAS', descricao: 'Aguardando designação de relator na Comissão de Assuntos Sociais', responsavel: undefined, diasNaEtapa: 40, temAtraso: false },
    { id: 'm12-3', proposicaoId: '12', data: '2024-01-19', orgao: 'CAS', descricao: 'Encaminhado à Comissão de Assuntos Sociais após aprovação na CCJ', responsavel: 'Sen. Marcio Bittar', diasNaEtapa: 30, temAtraso: false },
    { id: 'm12-2', proposicaoId: '12', data: '2023-12-20', orgao: 'CCJ — Senado', descricao: 'Aprovado na CCJ com voto favorável à constitucionalidade', responsavel: 'Sen. Esperidião Amin', diasNaEtapa: 245, temAtraso: false },
    { id: 'm12-1', proposicaoId: '12', data: '2023-04-19', orgao: 'Senado Federal', descricao: 'Apresentação do PL do Marco Legal da Inteligência Artificial', responsavel: 'Sen. Eduardo Gomes', diasNaEtapa: 0, temAtraso: false },
  ],
}

// Gera movimentações genéricas para proposições sem mock específico
export function getMovimentacoes(proposicaoId: string, proposicao: {
  dataApresentacao: string
  dataUltimaMovimentacao: string
  orgaoOrigem: string
  orgaoAtual: string
}): MovimentacaoTramitacao[] {
  if (MOVIMENTACOES_MOCK[proposicaoId]) return MOVIMENTACOES_MOCK[proposicaoId]

  return [
    {
      id: `m${proposicaoId}-3`,
      proposicaoId,
      data: proposicao.dataUltimaMovimentacao,
      orgao: proposicao.orgaoAtual,
      descricao: `Aguardando deliberação em ${proposicao.orgaoAtual}`,
      diasNaEtapa: 45,
      temAtraso: false,
    },
    {
      id: `m${proposicaoId}-2`,
      proposicaoId,
      data: proposicao.dataApresentacao,
      orgao: proposicao.orgaoOrigem,
      descricao: `Encaminhado para ${proposicao.orgaoAtual} para análise`,
      diasNaEtapa: 120,
      temAtraso: false,
    },
    {
      id: `m${proposicaoId}-1`,
      proposicaoId,
      data: proposicao.dataApresentacao,
      orgao: proposicao.orgaoOrigem,
      descricao: 'Apresentação e leitura da proposição em plenário',
      diasNaEtapa: 0,
      temAtraso: false,
    },
  ]
}
